## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import gkey

# Configure gmaps API key
gmaps.configure(api_key=gkey)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/Weather_Database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Mar Del Plata,AR,-38.0023,-57.5575,59.02,62,0,11.99,clear sky
1,1,Bhadrachalam,IN,17.6667,80.8833,74.34,97,99,2.33,overcast clouds
2,2,Ushuaia,AR,-54.8000,-68.3000,27.61,96,65,4.59,light snow
3,3,Hilo,US,19.7297,-155.0900,76.80,91,90,10.36,moderate rain
4,4,Kruisfontein,ZA,-34.0033,24.7314,49.89,60,87,17.76,overcast clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
3,3,Hilo,US,19.7297,-155.0900,76.80,91,90,10.36,moderate rain
6,6,Faanui,PF,-16.4833,-151.7500,80.38,70,28,19.28,scattered clouds
8,8,Cape Coast,GH,5.1053,-1.2466,78.58,88,63,9.48,broken clouds
12,12,Atuona,PF,-9.8000,-139.0333,77.50,80,39,18.88,light rain
14,14,Byron Bay,AU,-28.6500,153.6167,75.06,45,5,5.01,clear sky
16,16,Matara,LK,5.9485,80.5353,78.17,88,91,14.23,overcast clouds
17,17,Rikitea,PF,-23.1203,-134.9692,75.09,80,12,11.12,light rain
19,19,Alofi,NU,-19.0595,-169.9187,78.39,70,47,13.13,scattered clouds
25,25,Saint George,US,37.1041,-113.5841,77.47,15,1,0.00,clear sky
31,31,Vila Velha,BR,-20.3297,-40.2925,78.75,78,90,12.66,overcast clouds

In [5]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.count()

City_ID                220
City                   220
Country                220
Lat                    220
Lng                    220
Max Temp               220
Humidity               220
Cloudiness             220
Wind Speed             220
Current Description    220
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
preferred_cities_df.dropna()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
3,3,Hilo,US,19.7297,-155.0900,76.80,91,90,10.36,moderate rain
6,6,Faanui,PF,-16.4833,-151.7500,80.38,70,28,19.28,scattered clouds
8,8,Cape Coast,GH,5.1053,-1.2466,78.58,88,63,9.48,broken clouds
12,12,Atuona,PF,-9.8000,-139.0333,77.50,80,39,18.88,light rain
14,14,Byron Bay,AU,-28.6500,153.6167,75.06,45,5,5.01,clear sky
...,...,...,...,...,...,...,...,...,...,...
666,666,Miri,MY,4.4148,114.0089,79.00,90,100,4.36,overcast clouds
667,667,Bundaberg,AU,-24.8500,152.3500,80.89,32,0,4.61,clear sky
668,668,Cabedelo,BR,-6.9811,-34.8339,75.87,80,38,16.20,scattered clouds
670,670,Yulara,AU,-25.2406,130.9889,80.44,17,69,18.41,broken clouds
673,673,Port Augusta,AU,-32.5000,137.7667,75.34,30,0,8.39,clear sky

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
3,Hilo,US,76.80,moderate rain,19.7297,-155.0900,
6,Faanui,PF,80.38,scattered clouds,-16.4833,-151.7500,
8,Cape Coast,GH,78.58,broken clouds,5.1053,-1.2466,
12,Atuona,PF,77.50,light rain,-9.8000,-139.0333,
14,Byron Bay,AU,75.06,clear sky,-28.6500,153.6167,
16,Matara,LK,78.17,overcast clouds,5.9485,80.5353,
17,Rikitea,PF,75.09,light rain,-23.1203,-134.9692,
19,Alofi,NU,78.39,scattered clouds,-19.0595,-169.9187,
25,Saint George,US,77.47,clear sky,37.1041,-113.5841,
31,Vila Velha,BR,78.75,overcast clouds,-20.3297,-40.2925,

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": gkey
}

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [9]:
# 7. Drop the rows where there is no Hotel Name.
clean_hotel_df = hotel_df.dropna()

In [10]:
# 8a. Create the output File (CSV)
output_data_file = "WeatherPy_Vacation.csv"
# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))